name: App CI

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  # Build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
        
      # Install
      - name: INSTALL
        run: npm ci

      # Build
      - name: BUILD
        run: npm run build

      # Upload dist artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  # Deploy to gh pages
  deploy:
    name: Deploy
    # Deploy only for main branch
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    # Manual deployment
    # See https://devblogs.microsoft.com/devops/i-need-manual-approvers-for-github-actions-and-i-got-them-now/
    # environment:
    #   name: pchmn.github.io/vite-react-ts-ghactions-template
    #   url: https://pchmn.github.io/vite-react-ts-ghactions-template/
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      # Download dist artifacts
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      # Deploy dist folder to gh pages
      - name: DEPLOY
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
